### ISSUE TITLE
[TODO] Add Apple Silicon Continuous Integration workflow

### ISSUE THREAD

**Issue by BigslimVdub** [arqma/arqma#299]
Currently, GH does not support M1 workflows however there may be additions in early 2022 per [notes here](https://github.com/actions/virtual-environments/issues/2187). 

This is just a placeholder as to not forget to add this once GH provides the environment for building M1 support since many mac users are moving towards Apple silicon-based hardware, and Intel is towards the end of life for Mac support which GH currently supports.

**Comment by BigslimVdub** [comment]
Additional reading material for Xcode 13 and "cloud" ci use with GIT:
https://developer.apple.com/documentation/Xcode/About-Continuous-Integration-and-Delivery-with-Xcode-Cloud

**Comment by ArqTras** [comment]
Test

**Comment by ArqTras** [comment]
.

**Comment by malbit** [comment]
[Apple Sillicon CI + native depends cross-compile build](https://github.com/arqma/arqma/pull/297/commits/9764cec13b4913fcb18e9dd226dacb1aefe97972) 

@BigslimVdub you did ask for it. Did you?

**Comment by ArqTras** [comment]
looks like solved , thanks
