### ISSUE TITLE
Compilation error for version 0.2

### ISSUE THREAD

**Issue by pndiku** [arqma/arqma#37]
Trying to compile from git master and getting error:

`In file included from /usr/local/src/arqma/src/config/cryptonote.h:9:0,
                 from /usr/local/src/arqma/src/cryptonote_config.h:169,
                 from /usr/local/src/arqma/src/common/command_line.cpp:36:
/usr/local/src/arqma/src/config/testnet.h:26:3: error: uninitialized const member ‘cryptonote::config_t::GENESIS_NONCE’
   };
   ^
make[2]: *** [src/common/CMakeFiles/obj_common.dir/command_line.cpp.o] Error 1
make[1]: *** [src/common/CMakeFiles/obj_common.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by ArqTras** [comment]
Give us 20 - 30 min update branch and hash tag

**Comment by malbit** [comment]
Besides. 
Branch master is an Development branch and we are not guarantee them will work. At every Hard-Fork we are preparing HF branch with Tagged commits and those versions are 100% checked and fully operational. For HF_10 branch is: release-v0.2 and tag: v0.2 (with further commits made to branch). You just need to checkout proper HF branch: 
git clone https://github.com/arqma/arqma.git && cd arqma && git submodule init && git submodule update
——>> git checkout release-v0.2 <<—— that command will switch your repository to proper Hard-Fork branch

**Comment by pndiku** [comment]
I first tried it with v0.2 and it had the error, which is why I tried git master.

**Comment by ArqTras** [comment]
What system version you use

**Comment by pndiku** [comment]
I'm using Centos 7, cmake v3, boost v1.58, gcc v4.8.5

**Comment by ArqTras** [comment]
Update boost to 
https://sourceforge.net/projects/boost/files/boost/1.68.0/boost_1_68_0.tar.bz2
Ps thanks to You i found update to do in reader table

**Comment by pndiku** [comment]
First I tried using a newer version of gcc (6.3.1) and it's compiled properly with boost 1.58.

Maybe you should update your documentation to specify a minimum gcc requirement?

**Comment by malbit** [comment]
Can you install cmake-3.12.1, gcc-8, g++-8 and boost minimum 1.62 please and check compilation then.
If issues will remain, please let us know then.

**Comment by pndiku** [comment]
I wrote above that it worked with gcc-6 and boost-1.58. And advised that you should update the documentation to state the minimum required version of gcc.

I'll close the ticket now.
